### PR TITLE
Assembly

### PR DESCRIPTION
**Pull request by HannesWell**
- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

This PR aims to remove the execution-sections of the `maven-assembly-plugin` used in the child-module poms that are only declared in the pluginManagement section and therefore never run.

This PR also corrects the `mainClass` element in the `matheclipse-discord/pom.xml` whoose value starts with `class>` . @axkr or is this intentional?

@axkr do you use the `maven-assembly-plugin` in some manual Maven executions to assemble fat jars? Because `assembly` is not executed in the build (because it was only configured in the plug-in management). If you don't use it somewhere else the entire plug-in could be removed.

### CODE REVIEW

**Review by axkr — APPROVED** [review]

**Review by axkr — APPROVED** [review]

**Comment by HannesWell** [comment]
@axkr do you use the `maven-assembly-plugin` in some manual Maven executions for example to assemble fat jars? Or can the plug-in configuration entirely be removed?

**Comment by axkr** [comment]
> @axkr do you use the `maven-assembly-plugin` in some manual Maven executions for example to assemble fat jars? Or can the plug-in configuration entirely be removed?

The fat JAR generation is described here, but I never used it for my own purposes:
https://github.com/axkr/symja_android_library/wiki/Maven-usage

**Comment by HannesWell** [comment]
@axkr 

> > @axkr do you use the `maven-assembly-plugin` in some manual Maven executions for example to assemble fat jars? Or can the plug-in configuration entirely be removed?
> 
> The fat JAR generation is described here, but I never used it for my own purposes: https://github.com/axkr/symja_android_library/wiki/Maven-usage

Ah, thanks for the link. I missed that in my search.

Would you like to keep it for others or can I entirely remove it?
Even if we remove it here, down-stream users could still set up a similar `maven-assembly-plugin` configuration in their pom where they have the symja dependencies they want to include.

**Comment by axkr** [comment]
> Would you like to keep it for others or can I entirely remove it?
> Even if we remove it here, down-stream users could still set up a similar `maven-assembly-plugin` configuration in their pom where they have the symja dependencies they want to include.

you can remove it.

**Pull request merged**
