### PR TITLE
[Rationalization] add exact rationalization of floats (#417)

### PR DESCRIPTION
**Pull request by HannesWell**
- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

This PR adds `F.fractionExact()` to exactly represent any given double value by an `IExpr` (usually an `IFraction` but for very small values fractions do not work due to overflowing denominators). The computed `IExpr` always results to the same given value when evaluated to double (using `IExpr.evalDouble()`). This can be used to rationalize all floating-point values before evaluation and could help to solve issue #417.

The advantage of this method is it works for all double values, it returns exact representations of double values and it is very fast thanks to the algorithm in BigFraction (in my very simple benchmarks `F.fractionExact()` was about three times faster than `F.fractionConvergent()`). 

The only downside is, that the computed fractions are not always very nice. The following code
```
    List<Double> interestingValues = List.of(2.2, 0.7, 3.0, 0.1, 1.E-8, 1.E-4, 1.E7);
    for (Double value : interestingValues) {
      System.out.println();
      System.out.println("Value: " + value);
      System.out.println("Exact: " + F.fractionExact(value));
      System.out.println("Convergent: " + F.fractionConvergent(value));
    }
```
has the following result:
```
Value: 2.2
Exact: 2476979795053773/1125899906842624
Convergent: 11/5

Value: 0.7
Exact: 3152519739159347/4503599627370496
Convergent: 7/10

Value: 3.0
Exact: 3
Convergent: 3

Value: 0.1
Exact: 1/10
Convergent: 1/10

Value: 1.0E-11
Exact: 1/100000000000
Convergent: 0

Value: 1.0E-4
Exact: 1/10000
Convergent: 1/10000

Value: 1.0E7
Exact: 10000000
Convergent: 10000000
```

The results for the negative Power of ten are only so nice because of the "manual" handling with pre-defined constants.

Summed up, `F.fractionConvergent` seems to compute nicer results in terms that they correspond more to what a human would calculate. Therefore I'm thinking about to further improve `F.fractionExact()` by first calling `F.fractionConvergent()` with only a few iterations and taking that result if it is already exact. If not then the current algorithm is taken. Then AbstractFractionSym.getIntegerOrPowerOfTen() should also be obsolete (which I actually don't like very much because it is arbitrary).
@axkr what do you think?

### CODE REVIEW

**Comment by HannesWell** [comment]
On the other hand there could be two `fractionExact` methods. One that is very fast and produces not so nice results and one that tries the approach mentioned above and creates a bit "nicer" results.

**Comment by HannesWell** [comment]
> On the other hand there could be two `fractionExact` methods. One that is very fast and produces not so nice results and one that tries the approach mentioned above and creates a bit "nicer" results.

I have added `AbstractFractionSym.valueOfExactNice()` and updated the tests accordingly. In the expected tests result you can see the different behavior.

What's missing is a corresponding method in `F` and a better name for `valueOfExactNice()`.
@axkr do you have a better suggestion?

**Comment by axkr** [comment]
> do you have a better suggestion?

The name is OK, I think the new method doesn`t need to be in the public API in `F.java`.

**Review by axkr — APPROVED** [review]

**Comment by HannesWell** [comment]
> > do you have a better suggestion?
> 
> The name is OK, I think the new method doesn't need to be in the public API in `F.java`.

While struggling to find a better name, I would nevertheless like include it into the public API of F.
The problem could be avoided if `F.fractionExact` would accept a boolean flag as second argument that controls which version is used: `public static IExpr fractionExact(final double value, final boolean attemptNiceFraction)`

I think this would be a good compromise. Since it is (not yet?) used somewhere else in Symja I fear that it would otherwise be removed on day because it is assumed to be unused.

**Comment by HannesWell** [comment]
IMHO this is fine and I'm going to squash-and-merge this now.
If there is demand for further improvements we can apply them in a subsequent change.

**Pull request merged**
