### PR TITLE
[External] Remove unused package org.w3c.dom.mathml

### PR DESCRIPTION
**Pull request by HannesWell**
- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

It looks like the classes in package `org.w3c.dom.mathml` from the `matheclipse-external` module are not referenced in the Symja code base.
@axkr can be simply remove it?

### CODE REVIEW

**Comment by HannesWell** [comment]
I just launched the `org.matheclipse.io.eval.Console` and executed the example command:
```
>> ToExpression("1 + 2 - x \\times 4 \\div 5", TeXForm)
In[1]:= ToExpression("1 + 2 - x \\times 4 \\div 5", TeXForm)
Out[1]= 3-4/5*x
```
To me it looks like this works. I also verified that in `org.matheclipse.core.builtin.StringFunctions.ToExpression.evaluate` the following code is executed:

```
TeXParser texParser = new TeXParser(engine);
IExpr temp = texParser.toExpression(arg1.toString());
if (head.isPresent()) {
  return F.unaryAST1(head, temp);
}
return temp;
```
Additionally everything compiles successfully which the Maven build showed.

**Comment by axkr** [comment]
> Additionally everything compiles successfully which the Maven build demonstrated.

Yes the `org.w3c.dom` dependency is already delivered with the JDK

**Review by axkr — APPROVED** [review]

**Comment by HannesWell** [comment]
> > Additionally everything compiles successfully which the Maven build demonstrated.
> 
> Yes the `org.w3c.dom` dependency is already delivered with the JDK

Yes `org.w3c.dom` is part of the JDK/JRE but `org.w3c.dom.mathml` is not.

**Comment by HannesWell** [comment]
But to me it looks like it is not used and can therefore be removed.

**Pull request merged**
