### PR TITLE
division of two complex numbers "euclidean division for complex numbers, Gaussian Numbers"

### PR DESCRIPTION
**Pull request by OleksandrMariupol**
# Submit a pull request

Replace any "X" with your information. Please check the boxes below to confirm
that your pull request meets the requirements:

- [+] This pull request isn't a duplicate of an [existing one][1]
- [+] Commit messages are detailed 
- [+] Documentation has been updated to reflect changes
- [+] Tests have been added / updated to reflect changes

---

### What changes does this pull request make?

Adds test cases for ComplexSym.
Adds new method ComplexSym.integerPartDivisionGaussian

### What is the current behavior?

Finds integer part of division of two complex numbers "Gaussian Numbers Division"

### Does this pull request introduce any breaking changes?

No

### Other information:

-

[1]: https://github.com/axkr/symja_android_library/pulls

### CODE REVIEW

**Comment by axkr** [comment]
Thanks for the PR.

For checking if the input numbers are gaussian, you can use the `gaussianIntegers()` method and you can also throw a `IllegalArgumentException` if the numbers aren't gaussian.

https://github.com/axkr/symja_android_library/blob/6801e4d983ba78268a63cac669d3484baea1ed7e/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexSym.java#L388

Can you please also implement the signature `integerPartDivisionGaussian(final IInteger)`

Can your new method be used to implement the GCD for gaussian numbers here?
https://github.com/axkr/symja_android_library/blob/6801e4d983ba78268a63cac669d3484baea1ed7e/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Arithmetic.java#L1748

Example:
```
 GCD(-3+2*I, 14+21*I)
```
returns
```
2+3*I
```

**Comment by OleksandrMariupol** [comment]
Thank you very much for your answers. Could you please clarify some details. In this moment. I think method can have signature integerPartDivisionGaussian(final IInteger[] parm1, final IInteger[] parm2) if  we want use this method  in  the public IExpr e2ComArg(final IComplex c0, final IComplex c1) { }, it is  ok? And return type of the method shoud be IInteger or IComplex, what is better how do you think? And  I think we need second method in ComlexSym for fraction part of division, and we can use them both in e2ComArg for GSD, it is ok?

Regards

**Comment by axkr** [comment]
signature `IInteger[] integerPartDivisionGaussian(final IInteger[] parm1, final IInteger[] parm2) ` is ok. 

I suggest starting first with IInteger part and creating a second pull request for fraction part after finishing this pull request.

**Comment by OleksandrMariupol** [comment]
Thank you for your answer.

**Comment by OleksandrMariupol** [comment]
Could you specify one moment. It will be ok?, if I convert IInteger to IRational in method integerPartDivisionGaussian IRational a = (IRational) parm1[0], and then in the end IRational to IInteger? Or, we should, all time work with IInteger type in method?

Regards,

**Comment by axkr** [comment]
I would all time work with IInteger type in method.

**Comment by OleksandrMariupol** [comment]
Ok.Thank

**Comment by OleksandrMariupol** [comment]
Hi axkr, again). Now I am thinking about it will be ok, if the method return not only integer part of division but also fraction part of division of two Gaussian numbers, fraction part after integer part, in one IInteger array? And  we can use  this method for GCD method.

**Comment by OleksandrMariupol** [comment]
I updated question above, sorry sometimes formulate question from second attempts)

**Comment by axkr** [comment]
I suggest implementing a working  `GCD()` function by taking the easiest approach for you.

In Java implementation details can be refactored after you have a working method comparatively easy.

**Pull request merged**
