### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by OleksandrMariupol**
# Submit a pull request

Replace any "X" with your information. Please check the boxes below to confirm
that your pull request meets the requirements:

- [1] This pull request isn't a duplicate of an [existing one][1]
- [1] Commit messages are detailed 
- [1] Documentation has been updated to reflect changes
- [1] Tests have been added / updated to reflect changes

---

### What changes does this pull request make?

Created new functional interface. Changed  arccosh and arccot functions with the new mutableResultConditions2 function.

### What is the current behavior?

As example new logic for arccosh and arccot functions. Can use a similar approach for other functions of class IntervalSym, with using one of mutableResultConditions2 functions.

### Does this pull request introduce any breaking changes?

no

### Other information:

no

[1]: https://github.com/axkr/symja_android_library/pulls

### CODE REVIEW

**Comment by axkr** [comment]
I like the approach with the new `IExprProcessor` interface. Should I merge this already or would you like to do it for more methods?

**Comment by OleksandrMariupol** [comment]
Thank you! I would like to do it for more methods.

**Comment by OleksandrMariupol** [comment]
Hi axkr. I have already applied a new approach to most methods. Could you please check it? 
Thank you for your time.

Regards,

**Comment by axkr** [comment]
Are all interval test running?

You have to distinguish between an `IASTMutable`, which you can create like this

```
IASTMutable result = interval.copy();
```

and after that you can modify the arguments with the `set()` method.

Or you create a new IASTAppendable, which you can create like this

```
IASTMutable result = F.IntervalAlloc(interval.size());
```

and after that you can append the arguments with the `append()` method.

**Comment by OleksandrMariupol** [comment]
Can you please clarify what you mean by "Are all interval test running?" ? I did not find the tests for the class IntervalSym.  Are there some other tests that have already been written and I may have missed. 
Regards,

**Comment by axkr** [comment]
For example this JUnit test:
- https://github.com/axkr/symja_android_library/blob/d114248144c896eaf7f18c72ddfaff95db51f7e5/symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/LowercaseTestCase.java#L10419

In Eclikpse I use : "Run from inside the class editor":
- http://www.eclipseonetips.com/2014/06/16/run-a-single-junit-test-method-in-eclipse/

**Comment by OleksandrMariupol** [comment]
Hi axkr. 
Thanks a lot for pointing to the tests. Indeed there were 4 failed tests. I replaced set() with append(), and updated logic for the cases where the replaces were needed. Now all tests are passed. Please take a look when you have time and let me know if you have any other comments.

**Comment by axkr** [comment]
If you have time, please
- rename `mutableResultConditions2()` method and make it private and add some Javadoc 
- add some Javadoc to `IExprProcessor`
- add some Javadoc to the already available methods/class etc (Yes, I know, I didn't do it either)

I'm not sure for the next point, but I think `IExprProcessor` is very special only designed for the interval determination.
Then it should be added as a sub-interface directly in `IntervalSym`. What do you think?

```
...
public class IntervalSym {
	
	@FunctionalInterface
	public interface IExprProcessor {

		boolean process(IExpr min, IExpr max, IASTAppendable result, int index);

	}
...


}
```

**Comment by OleksandrMariupol** [comment]
Hi axkr. Thank you for your time. Sorry for the long answer, I was busy. I renamed mutable mutableResultConditions2() and added Javadoc for my methods.  I am very sorry, I can add javadoc to the rest of the methods what exactly I did in Methods, but not general Javadoc what these Methods do. Since I did not write these methods initially, and sometimes I don't quite understand exactly what they . If you have any questions please ask me

**Pull request merged**
